repos:
  # Use ruff for linting, formatting, and import sorting via uv
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check . --fix
        language: system
        types: [python]
        require_serial: false
      
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format .
        language: system
        types: [python]
        require_serial: false
      
      - id: pytest-coverage
        name: pytest with coverage
        entry: uv run pytest tests/ --cov=src --cov-config=pyproject.toml --cov-report=xml --cov-report=term -n auto
        language: system
        pass_filenames: false
        always_run: true
