repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "tests/"]
  # - repo: https://github.com/psf/black
  #   rev: 23.3.0
  #   hooks:
  #     - id: black
  #       args: ["--line-length", "100", "--preview"]
  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.1.0
  #   hooks:
  #     - id: flake8
  #       args: ["--show-source"]
  - repo: local
    hooks:
      - id: pytest-coverage
        name: pytest with coverage
        entry: uv run pytest tests/ --cov-config=pyproject.toml --cov-report=xml --cov-report=term
        language: system
        pass_filenames: false
        always_run: true

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.6
  #   hooks:
  #     - id: codespell
  #       args: ["--skip", "aider/website/docs/languages.md"]
  #       additional_dependencies:
  #         - tomli
