source "https://rubygems.org"

# Use the github-pages gem for GitHub Pages compatibility
gem "github-pages", group: :jekyll_plugins

# Theme
gem "just-the-docs", "~> 0.8.2"

# Other plugins you might want to add later:
# gem "jekyll-feed"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-redirect-from"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# If you have C extensions, uncomment the following line to use the correct platform
# platforms :ruby do
#   # platform-specific gems
# end
